# ---meta---
pretrain_exp_name: igae-warmup 
exp_name: igae
pretrain: true
train: true
# ----------

dataset:
  name: train/objaverse
  subset: square128

  scene_repartition: 
    objaverse: [0, 500]

injection_dataset: 
  name: train/imagenet/square128
  max_img: 45000
  split_ratio: 0.9

vae:
  pretrained_model_name_or_path: ostris/vae-kl-f8-d16


# training
train_args:
  consistency:
    batch_size: 12

  injection:
    apply: True
    batch_size: 3
    
    losses:
      loss_mse: True
      loss_lpip: True
    
    regularizations:
      tv: True

  optim:
    n_epochs: 75
